name: Build README

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2    
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: update README
      run: |-
        python --version
        python update_readme.py
        cat README.md
    - name: push README if changed
      run: |-
        git diff
        git config --global user.email "readme-autoupdate@km.com"
        git config --global user.name "readme-autoupdate"
        git diff --quiet || (git add README.md && git commit -m "README autoupdate")
        git push        